### ISSUE TITLE
Document how to include, configure, and use library

### ISSUE THREAD

**Issue by ralphpina** [patxibocos/poetimizely#18]
Consumers should know how to:
- include the library in their projects
- how to configure it so it generates the code they want
- how to access and use the generated code

We have already started documenting this in various Google Docs.
- including and configuration docs are started [here](https://docs.google.com/document/d/1roagdVV8rneMmwLnumhaMzeY1EhUpYuUyfs10zDHPwg).
- features is documented [here](https://docs.google.com/document/d/1XJap6OKnzAM-C4GoL1Ubs2zKRzJSlIdzcvddOOE2Z7Q).

The docs should probably be in the README. Should we also setup GitHub pages for a fancy website?

**Comment by patxibocos** [comment]
Cool, I would start updating the `README.md` with the details of how the generated code will look like and how to use it, because that is something I would say is stable now.

**Comment by ralphpina** [comment]
If you're working on other things I can take this 🙂. I just wanted to add these issues to make it easier to collaborate.
