### ISSUE TITLE
Configure Actions to publish the plugin when a release is created in GitHub

### ISSUE THREAD

**Issue by patxibocos** [patxibocos/poetimizely#20]
GitHub actions' workflows can be triggered when a new release is done
https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release
So we should:
- Create a GitHub workflow to run the `publishPlugins` task
- Store Gradle publish key and secret as secrets in the repo
- Run the task: `./gradlew publishPlugins -Pgradle.publish.key=<GRADLE_PUBLISH_KEY> -Pgradle.publish.secret=<GRADLE_PUBLISH_SECRET>`

![image](https://user-images.githubusercontent.com/4415614/77871769-f76afa00-71f9-11ea-8891-e53ee943bd98.png)

**Comment by ralphpina** [comment]
CI/CD for the win 😉.
