### ISSUE TITLE
Write a blog post to announce

### ISSUE THREAD

**Issue by ralphpina** [patxibocos/poetimizely#25]
We should write a post to share in social media and get feedback.

**Comment by patxibocos** [comment]
I was thinking on writing something in my Medium, but it was going to be focused on the tech stuff. So writing a separate/dedicated article to announce it makes sense to me 🙂

**Comment by patxibocos** [comment]
✔️ https://medium.com/@patxi/announcing-poetimizely-library-94c4e525f7e0
